name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Zip Lambda function
      run: zip -r function.zip lambda_function.py

    - name: Create Lambda function with high config
      run: |
        FUNCTION_NAME="data-cleaner-$(date +%s)"
        aws lambda create-function \
          --function-name $FUNCTION_NAME \
          --runtime python3.9 \
          --role arn:aws:iam::<your-account-id>:role/<lambda-role-name> \
          --handler lambda_function.lambda_handler \
          --zip-file fileb://function.zip \
          --timeout 900 \
          --memory-size 10240 \
          --ephemeral-storage '{"Size":10240}'
